name: Publish Expo Package to NPM

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Test the build process
        run: npm run build

      - name: Verify package contents (dry run)
        run: npm pack --dry-run

      - name: Check for any issues
        run: npm run check-types

      - name: Get package version
        id: version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: check_tag
        run: |
          TAG=v${{ steps.version.outputs.VERSION }}
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping publish."
            echo "EXISTS=true" >> $GITHUB_OUTPUT
          else
            echo "Tag $TAG does not exist."
            echo "EXISTS=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Tag and Release
        if: steps.check_tag.outputs.EXISTS == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: Release v${{ steps.version.outputs.VERSION }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        if: steps.check_tag.outputs.EXISTS == 'false'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
